server:
  port: 3344
  
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          passphrase: longjie001
          uri: https://github.com/clarklj001/springcloud-config.git
#          uri: git@github.com:clarklj001/springcloud-config.git
          skip-ssl-validation: true
          search-paths:
          - springcloud-config
      label: master
     
  rabbitmq:
    host: localhost 
    port: 5672
    username: guest
    password: guest
      
#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: config-center(${server.port})
    prefer-ip-address: true
   
#  server:
  #关闭自我保护机制，保证不可用服务被即时删除
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000
      
    
