server:
  port: 8010
  
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样值介于0和1之间，1表示全部采集
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

      
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  
logging:
  level:
    de.killbuqs.springcloud.service.PaymentService: debug